# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
#install: pip install -U tox-travis
- pip install coveralls
- python setup.py install
# Command to run tests, e.g. python setup.py test
#script: tox
before_install:
- pip install coverage
- pip install matplotlib
- pip install scipy
- sudo apt-get install -qq python-numpy python-scipy python-matplotlib

script: 
- coverage run --source=sept_example setup.py test
- coverage report -m
after_success: coveralls
# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
language: python
python: 2.7
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: yaraki0912
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: yaraki0912/sept_example
    python: 3.6
